### ISSUE TITLE
Fix error when running install

### ISSUE THREAD

**Issue by andre-matulionis-ifood** [hendrikswan/pluralsight-ts-advanced-types#2]
When I tried to install the packages, an error ocurred. Happening both in npm and in yarn.

Since the output complained about something about the `canvas` project, I tried upgrading it to 2.8.0, and it worked.

If you'd accept it, I will gladly send a PR with this adjustment.

Here is the output when I run `yarn`:

```
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.16.1 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v83-linux-glibc-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v83-linux-glibc-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v83-linux-glibc-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.0 and node@14.16.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v83-linux-glibc-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.16.1 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.16.1 | linux | x64
gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/andre/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/andre/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/andre/.cache/node-gyp/14.16.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/andre/.cache/node-gyp/14.16.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/andre/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/andre/.cache/node-gyp/14.16.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/andre/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.8.0-59-generic
gyp ERR! command "/home/andre/.nvm/versions/node/v14.16.1/bin/node" "/home/andre/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/andre/.nvm/versions/node/v14.16.1/bin/node /home/andre/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.8.0-59-generic
node-pre-gyp ERR! command "/home/andre/.nvm/versions/node/v14.16.1/bin/node" "/home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas
node-pre-gyp ERR! node -v v14.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/andre/.nvm/versions/node/v14.16.1/bin/node /home/andre/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/andre/workspace/personal/pluralsight-ts-advanced-types/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
```

**Comment by lepris** [comment]
Thanks @andre-matulionis-ifood ! I was all sort of crazy things including installing python and Visual Studio with C++ support, which obviously didn't work.
